/*
 * Candy Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"crypto/tls"
	"crypto/x509"
	"log"
	"net/http"
	"os"
	"time"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "candy-server/candyAPI"
)

func err_code(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func getServer() *http.Server {
	router := sw.NewRouter()
	data, err := os.ReadFile("minica.pem")
	err_code(err)
	cp := x509.NewCertPool()
	cp.AppendCertsFromPEM(data)

	tls := &tls.Config{
		ClientCAs:  cp,
		ClientAuth: tls.RequireAndVerifyClientCert,
	}

	server := &http.Server{
		Handler:      router,
		Addr:         "127.0.0.1:3333",
		TLSConfig:    tls,
		WriteTimeout: 15 * time.Second,
		ReadTimeout:  15 * time.Second,
	}
	return server
}

func main() {
	server := getServer()
	log.Println("server start work")
	err := server.ListenAndServeTLS("minica.pem", "minica-key.pem")
	err_code(err)
}
