/*
 * Candy Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package candyAPI

type InlineResponse200 struct {
	Change int32 `json:"change,omitempty"`

	Thanks string `json:"thanks,omitempty"`
}
