build_client:
	@go build -o client ./cmd/client/main.go

build_server:
	@go build -o server ./cmd/server/main.go

run:
	@go run -o server ./cmd/server/main.go
	@go run -o client ./cmd/client/main.go -k 2