version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./server
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q", "localhost:8082/metrics"]
      interval: 10s
      timeout: 5s
      retries: 3

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./client -k 2
    ports:
      - "8083:8083"
    env_file: .env 
    depends_on:
      - server
    networks:
      - backend

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deployments/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deployments/docker/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    networks:
      - backend
    depends_on:
      - server

  grafana:
    image: grafana/grafana-enterprise:latest
    volumes:
      - ./deployments/docker/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - prometheus

networks:
  backend: