build:
	@docker-compose build --no-cache
up:
	@docker-compose up -d

down:
	@docker-compose down

logs:
	@docker-compose logs -f

prometheus:
	@open http://localhost:9090

grafana:
	@open http://localhost:3000